version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
       - npm install -g @angular/cli@11.2.3

artifacts:
  files:
     - '**/*'
  discard-paths: no
  base-directory: build
